autoInstallPeers: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - less
  - lmdb
  - msgpackr-extract
  - nx
  - unrs-resolver

overrides:
  '@dockbite/c2pa-ts': link:../c2pa-ts
